name: Documentation

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published
      
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      with:
        fetch-depth: 0

    - name: Setup Micromamba
      uses: mamba-org/setup-micromamba@0dea6379afdaffa5d528b3d1dabc45da37f443fc  # v2.0.4
      with:
        environment-name: TEST
        init-shell: bash
        create-args: >-
          python=3 --file requirements.txt --channel conda-forge

    - name: Install library
      run: |
        python -m pip install -e . --no-deps --force-reinstall

    - name: Build documentation
      run: >
        set -e
        && make html

    - name: Deploy
      if: success() && github.event_name == 'release'
      uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e  # v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
